### ISSUE TITLE
Does the follow method for SpeedController(s) preserve inversion?

### ISSUE THREAD

**Issue by GCalizaya** [FirebirdRobotics/Robot2020#2]
Just want to make sure PID_ShooterSubsystem works as intended.

**Comment by ricefarmchild** [comment]
ah you're right. I'll change it. also I looked at the single for-loop code but I think there's some issues with it (or at the very least I'm confused). I'll talk it over with you monday, but if you have time can you add comments to it describing what's happening? thanks
